name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # для коммитов в основную ветку
    tags:
      - 'v*'  # для пуша тегов (например v1.0.0)

jobs:
  lint-and-test:
    name: Линтинг и тесты
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # укажи свою версию Go

      - name: Установить зависимости
        run: go mod tidy

      - name: Запуск тестов
        run: go test ./...

  publish-docker:
    name: Публикация в DockerHub
    runs-on: ubuntu-latest
    needs: lint-and-test  # этот job будет зависеть от первого job'а

    if: startsWith(github.ref, 'refs/tags/')  # выполняется только при пуше тега

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Логин в DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Debug GitHub Ref
        run: |
          echo "GitHub Ref: ${{ github.ref }}"

      - name: Сборка Docker-образа
        run: |
          docker build -t my-dockerhub-username/my-app:$GITHUB_SHA .

      - name: Публикация Docker-образа
        run: |
          docker push pentanir/my-app:$GITHUB_SHA
          IMAGE_TAG="${GITHUB_REF#refs/tags/}"
          docker tag pentanir/my-app:$GITHUB_SHA pentanir/my-app:$IMAGE_TAG
          docker push pentanir/my-app:$IMAGE_TAG
          docker tag pentanir/my-app:$GITHUB_SHA pentanir/my-app:latest
          docker push pentanir/my-app:latest
