name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # для коммитов в основную ветку
    tags:
      - 'v*'  # для пуша тегов (например v1.0.0)

jobs:
  lint-and-test:
    name: Линтинг и тесты
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # укажи свою версию Go

      - name: Установить зависимости
        run: go mod tidy

      - name: Запуск тестов
        run: go test ./...

  publish-docker:
    name: Публикация в DockerHub
    runs-on: ubuntu-latest
    needs: lint-and-test  # этот job будет зависеть от первого job'а

    if: startsWith(github.ref, 'refs/tags/')  # запускается только для тегов

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Логин в DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Сборка Docker-образа
        run: |
          docker build -t my-dockerhub-username/my-app:$GITHUB_SHA .

      - name: Публикация Docker-образа
        run: |
          docker push my-dockerhub-username/my-app:$GITHUB_SHA
          docker tag my-dockerhub-username/my-app:$GITHUB_SHA my-dockerhub-username/my-app:${GITHUB_REF#refs/tags/}
          docker push my-dockerhub-username/my-app:${GITHUB_REF#refs/tags/}
