name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # реагирует на теги, например v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: |
          docker build -t my-app:$GITHUB_SHA .

      - name: Push Docker image to DockerHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag my-app:$GITHUB_SHA my-dockerhub-username/my-app:$GITHUB_SHA
          docker push my-dockerhub-username/my-app:$GITHUB_SHA
